### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by icebob** [compactr/compactr.js#11]
Hi,

nice job! Is compactr stable? Has no memory leak...etc?
I plan to add it to my [Moleculer](https://github.com/ice-services/moleculer) microservices framework as a new serializer.

**Comment by fed135** [comment]
@icebob  Right now it should be stable enough. If you do find any issues with it, just ping me and I'll get on it asap. Also, lemme know if you need any help ;)

**Comment by icebob** [comment]
Do you have any documentation about types in schema?
